### ISSUE TITLE
Consider dropping compressdocs.sh with our own implementation for compressed man pages

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/ypkg#30]
Copied from the commit message:

This works as-is, however, we may want to drop compressdocs.sh with
our own implementation in python. It will need to:

- Determine man page files or just walk $installdir/usr/share/man $installdir/usr/man
- Skip compression if already compressed (look for .gz, .bz2 append)
- Compress with the highest level of gzip compression and append with .gz
- Look for hardlinks or symlinks and handle them as needed

**Comment by ReillyBrogan** [comment]
FWIW man-db 2.9.2 also added support for zstd-compressed man files.

**Comment by joebonrichie** [comment]
Thanks, zstd would work as well! The man pages will compress pretty well either way
