### ISSUE TITLE
Switch back to full fakeroot for package building to prevent build failures

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/ypkg#92]
In [this commit](https://github.com/getsolus/ypkg/commit/bcf1b168bbb8034f25567862ffd1b2ec3a18f690) we switched to "Only enable fakeroot during the install & check steps"

The reasoning was to reduce the overhead of package building and reduce build times.
Unfortunately, this has caused multiple packages to fail to build. In turn this has caused us to spend time helping packagers find out why packages were not building and help fix them. We have traded one time sink for another.

For now, let's switch back to using full fakeroot.

**Comment by silkeh** [comment]
This was resolved in #93, closing!
